// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Img2base(arg1) {
  return window['go']['main']['App']['Img2base'](arg1);
}

export function RssFeedAdd(arg1) {
  return window['go']['main']['App']['RssFeedAdd'](arg1);
}
