// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Img2base(arg1:string):Promise<main.Response>;

export function RssFeedAdd(arg1:string):Promise<main.Response>;
